### ISSUE TITLE
fixes and new Ruby versions for ruby/setup-ruby,

### ISSUE THREAD

**Issue by aaf-terraform** [ausaccessfed/aaf-mdqt#48]
change this to \(see https://github\.com/ruby/setup\-ruby\#versioning\):

uses: ruby/setup\-ruby@v1

v1\.202\.0

https://github.com/ausaccessfed/aaf-mdqt/blob/c6da8146e1b4e97e5cc03e95eeaedbbbbcc11997/.github/workflows/ruby.yml#L33-L36

```yaml

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

env:
  LANG: "en_GB.UTF-8"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.0']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    # uses: ruby/setup-ruby@v1
      uses: ruby/setup-ruby@a2bbe5b1b236842c1cb7dd11e8e3b51e0a616acc # v1.202.0
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Run tests
      run: bundle exec rake features

```
