### ISSUE TITLE
fixes and new Ruby versions for ruby/setup-ruby,

### ISSUE THREAD

**Issue by aaf-terraform** [ausaccessfed/aaf-mdqt#54]
change this to \(see https://github\.com/ruby/setup\-ruby\#versioning\):

uses: ruby/setup\-ruby@v1

v1\.229\.0

https://github.com/ausaccessfed/aaf-mdqt/blob/c512082e9de222e51d16d57173369b8878ca45cb/.github/workflows/ruby.yml#L33-L36

```yaml

    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    # uses: ruby/setup-ruby@v1
      uses: ruby/setup-ruby@354a1ad156761f5ee2b7b13fa8e09943a5e8d252 # v1.229.0
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically

```
