### ISSUE TITLE
fixes and new Ruby versions for ruby/setup-ruby,

### ISSUE THREAD

**Issue by aaf-terraform** [ausaccessfed/aaf-mdqt#56]
change this to \(see https://github\.com/ruby/setup\-ruby\#versioning\):

uses: ruby/setup\-ruby@v1

https://github.com/ausaccessfed/aaf-mdqt/blob/ff21a900e9723d3cf707ca1f9aadc4802812456b/.github/workflows/ruby.yml#L33-L35

```yaml

    - uses: actions/checkout@v4
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # Issue URL: https://github.com/ausaccessfed/aaf-mdqt/issues/48
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    # uses: ruby/setup-ruby@v1
      uses: ruby/setup-ruby@354a1ad156761f5ee2b7b13fa8e09943a5e8d252 # v1.229.0
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically

```
